
import "@/assets/styles/styles.css"
import "@/assets/styles/global.css"
import NavBar from "@/components/NavBar";
import Script from "next/script";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Artsy Coder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      <body>
        <NavBar />
            <main className="wrapper">
              {children}
            </main>
        <Footer />
        <Script src="/js/bootstrap.bundle.js" />
        </body>
    </html>
  );
}
